# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Jojo\PhD\VideoEnhancerPython\qt_gui\videoEnhancer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1040, 680))
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setStyleSheet("/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #202020;\n"
"    color: #fff;\n"
"    selection-background-color: #ff732d; \n"
"    selection-color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel:disabled \n"
"{\n"
"    color: #4e4e4e;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: #252525;\n"
"    border: none;\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar:disabled \n"
"{\n"
"    color: #4e4e4e;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: #424242;\n"
"    border: none;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #424242;\n"
"    border: none;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"    color: #fff;\n"
"    font-size: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #ff732d;\n"
"    color: #000;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"    background-color: #aaa;    \n"
"    margin-top: 5px;\n"
"    margin-bottom: 5px;\n"
"    height: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabBar-----*/\n"
"QTabBar \n"
"{\n"
"    background-color: transparent;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar \n"
"{\n"
"    border:none;\n"
"    left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab \n"
"{\n"
"    font-weight: bold;\n"
"    padding-left: 15px; \n"
"    padding-right: 15px; \n"
"    height: 25px;\n"
"    width: 60px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    border: 1px solid #333; \n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    color: #ff732d; \n"
"    font-weight: bold;\n"
"    border: 1px solid #1b1b1b;\n"
"    background-color: #1b1b1b;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected \n"
"{\n"
"    background-color: #424242;\n"
"    border: 1px solid #414141;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar:tab:selected:disabled \n"
"{\n"
"    color: #4e4e4e;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    color: #fff; \n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar:tab:!selected:disabled \n"
"{\n"
"    color: #4e4e4e;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    margin: 2px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: #ff732d;\n"
"    color: #000;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: #424242;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #424242;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:disabled \n"
"{\n"
"    color: #4e4e4e;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDockWidget-----*/\n"
"QDockWidget\n"
"{\n"
"    color : #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::title \n"
"{\n"
"    background-color: transparent;\n"
"    border: 1px solid #3a3a3a;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::close-button\n"
"{\n"
"    max-width: 14px;\n"
"    max-height: 14px;\n"
"    margin-top:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::float-button\n"
"{\n"
"    max-width: 14px;\n"
"    max-height: 14px;\n"
"    margin-top:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::close-button:hover\n"
"{\n"
"    border: none;\n"
"    background-color: #ff732d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::float-button:hover\n"
"{\n"
"    border: none;\n"
"    background-color: #ff732d;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeWidget\n"
"{\n"
"    show-decoration-selected: 0;\n"
"    selection-background-color: transparent; /* Used on Mac */\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    background-color: #292929;\n"
"    border: 1px solid #3a3a3a;\n"
"    padding: 5px;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color: #000;\n"
"    background-color: #ff732d;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #424242;\n"
"    color: #fff;\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    background-color: #9d9d9d;\n"
"    border: 1px solid #3a3a3a;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover \n"
"{\n"
"    background-color: #bebebe;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    color: #ff732d;\n"
"    border: 1px solid #3a3a3a;\n"
"    background-color: #1b1b1b;\n"
"    margin-top: 5.5ex;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title \n"
"{\n"
"    background-color: #1b1b1b;\n"
"    border: 1px solid #3a3a3a;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right 0px;\n"
"    border-radius: 0px;\n"
"    padding: 3px 30px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox \n"
"{\n"
"    background-color: #424242;\n"
"    border: 1px solid #3a3a3a;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:editable \n"
"{\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    background-color: #424242;\n"
"    border-left-width:1px;\n"
"    border-left-color: #777777;\n"
"    border-left-style: solid; \n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow \n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width:8px;\n"
"    height:8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow:on \n"
"{ \n"
"    top: 1px;\n"
"    left: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QListView\n"
"{\n"
"    background-color: #292929;\n"
"    border-left-style: solid; \n"
"    selection-background-color: #ff732d;\n"
"    selection-color: #000;\n"
"    color: #fff;\n"
"    padding: 10px;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #ff732d;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\"); /*To replace*/\n"
"    background-color: #ff732d;\n"
"    border: 1px solid #ff732d;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #ff732d;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox-----*/\n"
"QSpinBox \n"
"{\n"
"    border: 1px solid #3a3a3a;\n"
"    min-height: 20px;\n"
"    min-width: 30px;\n"
"    border-radius : 2px;\n"
"    color : #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    background-color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox:hover \n"
"{\n"
"    background-color: #333;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button \n"
"{\n"
"    background-color: #777777;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover \n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed \n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow \n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button \n"
"{\n"
"    border-bottom-right-radius:2px;\n"
"    background-color: #777777;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button:hover \n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed \n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow \n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton{\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked\n"
"{ \n"
"    border: 2px inset #424242; \n"
"    border-radius: 6px; \n"
"    background-color:  #323232;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover\n"
"{ \n"
"    border: 2px solid #ff732d; \n"
"    border-radius: 5px; \n"
"    background-color:  #323232;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked\n"
"{ \n"
"    border: 2px inset #424242; \n"
"    border-radius: 5px; \n"
"    background-color: #ff732d; \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 2px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar \n"
"{\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    background-color: #252525;\n"
"\n"
"}\n"
"\n"
"\n"
"QStatusBar::item \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSizeGrip-----*/\n"
"QSizeGrip \n"
"{\n"
"    background-color: image(\"./ressources/sizegrip.png\"); /*To replace*/\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1063, 808))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vertLayoutLeft = QtWidgets.QVBoxLayout()
        self.vertLayoutLeft.setObjectName("vertLayoutLeft")
        self.label_vertLayout_Setup = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_vertLayout_Setup.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_vertLayout_Setup.setFont(font)
        self.label_vertLayout_Setup.setStyleSheet("/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"}")
        self.label_vertLayout_Setup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_vertLayout_Setup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_vertLayout_Setup.setObjectName("label_vertLayout_Setup")
        self.vertLayoutLeft.addWidget(self.label_vertLayout_Setup)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.vertLayoutLeft.addWidget(self.line_2)
        self.left_horizontalLayout_LoadVideos = QtWidgets.QHBoxLayout()
        self.left_horizontalLayout_LoadVideos.setContentsMargins(10, 10, -1, 10)
        self.left_horizontalLayout_LoadVideos.setSpacing(6)
        self.left_horizontalLayout_LoadVideos.setObjectName("left_horizontalLayout_LoadVideos")
        self.label_LoadVideos = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_LoadVideos.setObjectName("label_LoadVideos")
        self.left_horizontalLayout_LoadVideos.addWidget(self.label_LoadVideos)
        self.left_pushButton_loadVideos = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.left_pushButton_loadVideos.setObjectName("left_pushButton_loadVideos")
        self.left_horizontalLayout_LoadVideos.addWidget(self.left_pushButton_loadVideos)
        self.vertLayoutLeft.addLayout(self.left_horizontalLayout_LoadVideos)
        self.left_listWidget_videoList = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_listWidget_videoList.sizePolicy().hasHeightForWidth())
        self.left_listWidget_videoList.setSizePolicy(sizePolicy)
        self.left_listWidget_videoList.setMinimumSize(QtCore.QSize(150, 100))
        self.left_listWidget_videoList.setObjectName("left_listWidget_videoList")
        self.vertLayoutLeft.addWidget(self.left_listWidget_videoList)
        self.left_pushButton_clearVideoList = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.left_pushButton_clearVideoList.setObjectName("left_pushButton_clearVideoList")
        self.vertLayoutLeft.addWidget(self.left_pushButton_clearVideoList)
        self.left_horizontalLayout_LoadVideos_3 = QtWidgets.QHBoxLayout()
        self.left_horizontalLayout_LoadVideos_3.setContentsMargins(10, 10, -1, 10)
        self.left_horizontalLayout_LoadVideos_3.setSpacing(6)
        self.left_horizontalLayout_LoadVideos_3.setObjectName("left_horizontalLayout_LoadVideos_3")
        self.label_LoadVideos_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_LoadVideos_3.setObjectName("label_LoadVideos_3")
        self.left_horizontalLayout_LoadVideos_3.addWidget(self.label_LoadVideos_3)
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdNumber.setObjectName("lcdNumber")
        self.left_horizontalLayout_LoadVideos_3.addWidget(self.lcdNumber)
        self.vertLayoutLeft.addLayout(self.left_horizontalLayout_LoadVideos_3)
        self.left_horizontalLayout_selectPreview = QtWidgets.QHBoxLayout()
        self.left_horizontalLayout_selectPreview.setContentsMargins(10, 10, -1, 10)
        self.left_horizontalLayout_selectPreview.setSpacing(6)
        self.left_horizontalLayout_selectPreview.setObjectName("left_horizontalLayout_selectPreview")
        self.label_LoadVideos_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_LoadVideos_4.setObjectName("label_LoadVideos_4")
        self.left_horizontalLayout_selectPreview.addWidget(self.label_LoadVideos_4)
        self.left_comboBox_selectPreview = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_comboBox_selectPreview.sizePolicy().hasHeightForWidth())
        self.left_comboBox_selectPreview.setSizePolicy(sizePolicy)
        self.left_comboBox_selectPreview.setMinimumSize(QtCore.QSize(50, 0))
        self.left_comboBox_selectPreview.setObjectName("left_comboBox_selectPreview")
        self.left_horizontalLayout_selectPreview.addWidget(self.left_comboBox_selectPreview)
        self.vertLayoutLeft.addLayout(self.left_horizontalLayout_selectPreview)
        self.left_horizontalLayout_OutputFolder = QtWidgets.QHBoxLayout()
        self.left_horizontalLayout_OutputFolder.setContentsMargins(10, 10, -1, 10)
        self.left_horizontalLayout_OutputFolder.setSpacing(6)
        self.left_horizontalLayout_OutputFolder.setObjectName("left_horizontalLayout_OutputFolder")
        self.label_OutputFolder = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_OutputFolder.setObjectName("label_OutputFolder")
        self.left_horizontalLayout_OutputFolder.addWidget(self.label_OutputFolder)
        self.left_pushButton_OutputFolder = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.left_pushButton_OutputFolder.setObjectName("left_pushButton_OutputFolder")
        self.left_horizontalLayout_OutputFolder.addWidget(self.left_pushButton_OutputFolder)
        self.vertLayoutLeft.addLayout(self.left_horizontalLayout_OutputFolder)
        self.left_lineEdit_outputFolder = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.left_lineEdit_outputFolder.setObjectName("left_lineEdit_outputFolder")
        self.vertLayoutLeft.addWidget(self.left_lineEdit_outputFolder)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertLayoutLeft.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.vertLayoutLeft)
        self.vertLayoutMid = QtWidgets.QVBoxLayout()
        self.vertLayoutMid.setObjectName("vertLayoutMid")
        self.label_vertLayout_Preview = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_vertLayout_Preview.setFont(font)
        self.label_vertLayout_Preview.setStyleSheet("/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"}")
        self.label_vertLayout_Preview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_vertLayout_Preview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_vertLayout_Preview.setObjectName("label_vertLayout_Preview")
        self.vertLayoutMid.addWidget(self.label_vertLayout_Preview)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.vertLayoutMid.addWidget(self.line_3)
        self.mid_pushButton_startPreview = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mid_pushButton_startPreview.setObjectName("mid_pushButton_startPreview")
        self.vertLayoutMid.addWidget(self.mid_pushButton_startPreview)
        self.mid_pushButton_updatePreview = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mid_pushButton_updatePreview.setEnabled(False)
        self.mid_pushButton_updatePreview.setStyleSheet("/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #2e2e2e;\n"
"    color: #fff;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #787878;\n"
"    color: #959595;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #54aad3;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #2385b4;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    color: #54aad3;\n"
"    background-color: #450505;\n"
"    border: 2px solid #bd5355;\n"
"\n"
"}\n"
"\n"
"")
        self.mid_pushButton_updatePreview.setObjectName("mid_pushButton_updatePreview")
        self.vertLayoutMid.addWidget(self.mid_pushButton_updatePreview)
        self.mid_frame_LivePreview = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.mid_frame_LivePreview.setMinimumSize(QtCore.QSize(400, 200))
        self.mid_frame_LivePreview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame_LivePreview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame_LivePreview.setObjectName("mid_frame_LivePreview")
        self.mid_label_livePreview = QtWidgets.QLabel(self.mid_frame_LivePreview)
        self.mid_label_livePreview.setGeometry(QtCore.QRect(19, 0, 411, 201))
        self.mid_label_livePreview.setMinimumSize(QtCore.QSize(400, 200))
        self.mid_label_livePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_label_livePreview.setObjectName("mid_label_livePreview")
        self.vertLayoutMid.addWidget(self.mid_frame_LivePreview)
        self.mid_horizontalSlider_frame = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.mid_horizontalSlider_frame.setMinimumSize(QtCore.QSize(300, 0))
        self.mid_horizontalSlider_frame.setMaximum(3000)
        self.mid_horizontalSlider_frame.setSliderPosition(50)
        self.mid_horizontalSlider_frame.setOrientation(QtCore.Qt.Horizontal)
        self.mid_horizontalSlider_frame.setObjectName("mid_horizontalSlider_frame")
        self.vertLayoutMid.addWidget(self.mid_horizontalSlider_frame)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.vertLayoutMid.addWidget(self.line)
        self.mid_label_previewFrame = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mid_label_previewFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_label_previewFrame.setObjectName("mid_label_previewFrame")
        self.vertLayoutMid.addWidget(self.mid_label_previewFrame)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mid_label_startCropOff = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mid_label_startCropOff.setObjectName("mid_label_startCropOff")
        self.horizontalLayout_9.addWidget(self.mid_label_startCropOff)
        self.mid_lineEdit_startCropOff = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_lineEdit_startCropOff.sizePolicy().hasHeightForWidth())
        self.mid_lineEdit_startCropOff.setSizePolicy(sizePolicy)
        self.mid_lineEdit_startCropOff.setMinimumSize(QtCore.QSize(20, 0))
        self.mid_lineEdit_startCropOff.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.mid_lineEdit_startCropOff.setMaxLength(4)
        self.mid_lineEdit_startCropOff.setObjectName("mid_lineEdit_startCropOff")
        self.horizontalLayout_9.addWidget(self.mid_lineEdit_startCropOff)
        self.mid_label_endCropOff = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mid_label_endCropOff.setObjectName("mid_label_endCropOff")
        self.horizontalLayout_9.addWidget(self.mid_label_endCropOff)
        self.mid_lineEdit_endCropOff = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_lineEdit_endCropOff.sizePolicy().hasHeightForWidth())
        self.mid_lineEdit_endCropOff.setSizePolicy(sizePolicy)
        self.mid_lineEdit_endCropOff.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mid_lineEdit_endCropOff.setFont(font)
        self.mid_lineEdit_endCropOff.setMaxLength(4)
        self.mid_lineEdit_endCropOff.setObjectName("mid_lineEdit_endCropOff")
        self.horizontalLayout_9.addWidget(self.mid_lineEdit_endCropOff)
        self.mid_radioButton_cropVideo = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.mid_radioButton_cropVideo.setObjectName("mid_radioButton_cropVideo")
        self.horizontalLayout_9.addWidget(self.mid_radioButton_cropVideo)
        self.vertLayoutMid.addLayout(self.horizontalLayout_9)
        self.mid_label_cropVideos = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mid_label_cropVideos.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_label_cropVideos.setObjectName("mid_label_cropVideos")
        self.vertLayoutMid.addWidget(self.mid_label_cropVideos)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertLayoutMid.addItem(spacerItem1)
        self.mid_label_Histograms = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mid_label_Histograms.setObjectName("mid_label_Histograms")
        self.vertLayoutMid.addWidget(self.mid_label_Histograms)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mid_frame_leftHisto = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.mid_frame_leftHisto.setMinimumSize(QtCore.QSize(160, 180))
        self.mid_frame_leftHisto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame_leftHisto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame_leftHisto.setObjectName("mid_frame_leftHisto")
        self.mid_label_histOrig = QtWidgets.QLabel(self.mid_frame_leftHisto)
        self.mid_label_histOrig.setGeometry(QtCore.QRect(-4, -8, 171, 191))
        self.mid_label_histOrig.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_label_histOrig.setObjectName("mid_label_histOrig")
        self.horizontalLayout_4.addWidget(self.mid_frame_leftHisto)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.mid_frame_rigthHisto = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.mid_frame_rigthHisto.setMinimumSize(QtCore.QSize(160, 180))
        self.mid_frame_rigthHisto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame_rigthHisto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame_rigthHisto.setObjectName("mid_frame_rigthHisto")
        self.mid_label_equHist = QtWidgets.QLabel(self.mid_frame_rigthHisto)
        self.mid_label_equHist.setGeometry(QtCore.QRect(-4, -8, 171, 191))
        self.mid_label_equHist.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_label_equHist.setObjectName("mid_label_equHist")
        self.horizontalLayout_4.addWidget(self.mid_frame_rigthHisto)
        self.vertLayoutMid.addLayout(self.horizontalLayout_4)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox.setObjectName("checkBox")
        self.vertLayoutMid.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertLayoutMid.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.vertLayoutMid)
        self.vertLayoutRight = QtWidgets.QVBoxLayout()
        self.vertLayoutRight.setObjectName("vertLayoutRight")
        self.label_vertLayout_VideoSettings = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_vertLayout_VideoSettings.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_vertLayout_VideoSettings.setFont(font)
        self.label_vertLayout_VideoSettings.setStyleSheet("/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ff732d;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"\n"
"}")
        self.label_vertLayout_VideoSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_vertLayout_VideoSettings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_vertLayout_VideoSettings.setObjectName("label_vertLayout_VideoSettings")
        self.vertLayoutRight.addWidget(self.label_vertLayout_VideoSettings)
        self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.vertLayoutRight.addWidget(self.line_4)
        self.right_pushButton_calcHist = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_calcHist.setObjectName("right_pushButton_calcHist")
        self.vertLayoutRight.addWidget(self.right_pushButton_calcHist)
        self.right_pushButton_equalizeHist = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_equalizeHist.setObjectName("right_pushButton_equalizeHist")
        self.vertLayoutRight.addWidget(self.right_pushButton_equalizeHist)
        self.right_horizontalLayout_HistThreshold = QtWidgets.QHBoxLayout()
        self.right_horizontalLayout_HistThreshold.setContentsMargins(-1, 10, -1, 10)
        self.right_horizontalLayout_HistThreshold.setObjectName("right_horizontalLayout_HistThreshold")
        self.right_checkBox_useThreshold = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.right_checkBox_useThreshold.setObjectName("right_checkBox_useThreshold")
        self.right_horizontalLayout_HistThreshold.addWidget(self.right_checkBox_useThreshold)
        self.right_comboBox_chooseThreshold = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.right_comboBox_chooseThreshold.setMinimumSize(QtCore.QSize(100, 0))
        self.right_comboBox_chooseThreshold.setObjectName("right_comboBox_chooseThreshold")
        self.right_horizontalLayout_HistThreshold.addWidget(self.right_comboBox_chooseThreshold)
        self.vertLayoutRight.addLayout(self.right_horizontalLayout_HistThreshold)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.right_label_ThreshMin = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.right_label_ThreshMin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.right_label_ThreshMin.setObjectName("right_label_ThreshMin")
        self.horizontalLayout_5.addWidget(self.right_label_ThreshMin)
        self.right_lineEdit_ThreshMin = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.right_lineEdit_ThreshMin.setMinimumSize(QtCore.QSize(30, 0))
        self.right_lineEdit_ThreshMin.setObjectName("right_lineEdit_ThreshMin")
        self.horizontalLayout_5.addWidget(self.right_lineEdit_ThreshMin)
        self.right_label_ThreshMax = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.right_label_ThreshMax.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_label_ThreshMax.setObjectName("right_label_ThreshMax")
        self.horizontalLayout_5.addWidget(self.right_label_ThreshMax)
        self.right_lineEdit_ThreshMax = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.right_lineEdit_ThreshMax.setMinimumSize(QtCore.QSize(30, 0))
        self.right_lineEdit_ThreshMax.setObjectName("right_lineEdit_ThreshMax")
        self.horizontalLayout_5.addWidget(self.right_lineEdit_ThreshMax)
        self.vertLayoutRight.addLayout(self.horizontalLayout_5)
        self.right_pushButton_ApplyThreshold = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_ApplyThreshold.setObjectName("right_pushButton_ApplyThreshold")
        self.vertLayoutRight.addWidget(self.right_pushButton_ApplyThreshold)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.right_label_Gamma = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.right_label_Gamma.setObjectName("right_label_Gamma")
        self.horizontalLayout_6.addWidget(self.right_label_Gamma)
        self.right_horizontalSlider_gamma = QtWidgets.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_horizontalSlider_gamma.sizePolicy().hasHeightForWidth())
        self.right_horizontalSlider_gamma.setSizePolicy(sizePolicy)
        self.right_horizontalSlider_gamma.setMinimumSize(QtCore.QSize(200, 0))
        self.right_horizontalSlider_gamma.setMinimum(0)
        self.right_horizontalSlider_gamma.setMaximum(20)
        self.right_horizontalSlider_gamma.setSingleStep(1)
        self.right_horizontalSlider_gamma.setProperty("value", 10)
        self.right_horizontalSlider_gamma.setSliderPosition(10)
        self.right_horizontalSlider_gamma.setOrientation(QtCore.Qt.Horizontal)
        self.right_horizontalSlider_gamma.setObjectName("right_horizontalSlider_gamma")
        self.horizontalLayout_6.addWidget(self.right_horizontalSlider_gamma)
        self.right_pushButton_applyGamma = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_applyGamma.setObjectName("right_pushButton_applyGamma")
        self.horizontalLayout_6.addWidget(self.right_pushButton_applyGamma)
        self.vertLayoutRight.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.right_label_Brightness = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.right_label_Brightness.setObjectName("right_label_Brightness")
        self.horizontalLayout_7.addWidget(self.right_label_Brightness)
        self.right_horizontalSlider_brightness = QtWidgets.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_horizontalSlider_brightness.sizePolicy().hasHeightForWidth())
        self.right_horizontalSlider_brightness.setSizePolicy(sizePolicy)
        self.right_horizontalSlider_brightness.setMinimumSize(QtCore.QSize(200, 0))
        self.right_horizontalSlider_brightness.setMinimum(-255)
        self.right_horizontalSlider_brightness.setMaximum(255)
        self.right_horizontalSlider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.right_horizontalSlider_brightness.setObjectName("right_horizontalSlider_brightness")
        self.horizontalLayout_7.addWidget(self.right_horizontalSlider_brightness)
        self.right_pushButton_applyBright = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_applyBright.setObjectName("right_pushButton_applyBright")
        self.horizontalLayout_7.addWidget(self.right_pushButton_applyBright)
        self.vertLayoutRight.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.right_label_Contrast = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.right_label_Contrast.setObjectName("right_label_Contrast")
        self.horizontalLayout_8.addWidget(self.right_label_Contrast)
        self.right_horizontalSlider_contrast = QtWidgets.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_horizontalSlider_contrast.sizePolicy().hasHeightForWidth())
        self.right_horizontalSlider_contrast.setSizePolicy(sizePolicy)
        self.right_horizontalSlider_contrast.setMinimumSize(QtCore.QSize(200, 0))
        self.right_horizontalSlider_contrast.setMinimum(-127)
        self.right_horizontalSlider_contrast.setMaximum(127)
        self.right_horizontalSlider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.right_horizontalSlider_contrast.setObjectName("right_horizontalSlider_contrast")
        self.horizontalLayout_8.addWidget(self.right_horizontalSlider_contrast)
        self.right_pushButton_applyContr = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_applyContr.setObjectName("right_pushButton_applyContr")
        self.horizontalLayout_8.addWidget(self.right_pushButton_applyContr)
        self.vertLayoutRight.addLayout(self.horizontalLayout_8)
        self.right_checkBox_cannyEdgeDetector = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.right_checkBox_cannyEdgeDetector.setObjectName("right_checkBox_cannyEdgeDetector")
        self.vertLayoutRight.addWidget(self.right_checkBox_cannyEdgeDetector)
        self.right_checkBox_sharpen = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.right_checkBox_sharpen.setObjectName("right_checkBox_sharpen")
        self.vertLayoutRight.addWidget(self.right_checkBox_sharpen)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.vertLayoutRight.addItem(spacerItem4)
        self.right_pushButton_revertToOriginal = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pushButton_revertToOriginal.setObjectName("right_pushButton_revertToOriginal")
        self.vertLayoutRight.addWidget(self.right_pushButton_revertToOriginal)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.vertLayoutRight.addItem(spacerItem5)
        self.right_pushButton_ApplySettingsToAll = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.right_pushButton_ApplySettingsToAll.setFont(font)
        self.right_pushButton_ApplySettingsToAll.setStyleSheet("/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #97bf47;\n"
"    color: #fff;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #606060;\n"
"    color: #959595;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #54aad3;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #2385b4;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    color: #54aad3;\n"
"    background-color: #450505;\n"
"    border: 2px solid #bd5355;\n"
"\n"
"}\n"
"")
        self.right_pushButton_ApplySettingsToAll.setObjectName("right_pushButton_ApplySettingsToAll")
        self.vertLayoutRight.addWidget(self.right_pushButton_ApplySettingsToAll)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertLayoutRight.addItem(spacerItem6)
        self.right_label_info = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.right_label_info.setStyleSheet("/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-size: 10px;\n"
"\n"
"}")
        self.right_label_info.setObjectName("right_label_info")
        self.vertLayoutRight.addWidget(self.right_label_info, 0, QtCore.Qt.AlignHCenter)
        self.right_listWidget_info = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.right_listWidget_info.setLineWidth(2)
        self.right_listWidget_info.setObjectName("right_listWidget_info")
        self.vertLayoutRight.addWidget(self.right_listWidget_info)
        self.right_progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.right_progressBar.setProperty("value", 24)
        self.right_progressBar.setObjectName("right_progressBar")
        self.vertLayoutRight.addWidget(self.right_progressBar)
        self.horizontalLayout.addLayout(self.vertLayoutRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_vertLayout_Setup.setText(_translate("MainWindow", "Setup"))
        self.label_LoadVideos.setText(_translate("MainWindow", "Load videos: "))
        self.left_pushButton_loadVideos.setText(_translate("MainWindow", "Open"))
        self.left_pushButton_clearVideoList.setText(_translate("MainWindow", "clear list of videos"))
        self.label_LoadVideos_3.setText(_translate("MainWindow", "Number of Videos:"))
        self.label_LoadVideos_4.setText(_translate("MainWindow", "Select video for preview:"))
        self.label_OutputFolder.setText(_translate("MainWindow", "Output folder: "))
        self.left_pushButton_OutputFolder.setText(_translate("MainWindow", "Select"))
        self.label_vertLayout_Preview.setText(_translate("MainWindow", "Preview"))
        self.mid_pushButton_startPreview.setText(_translate("MainWindow", "start video preview"))
        self.mid_pushButton_updatePreview.setText(_translate("MainWindow", "update preview"))
        self.mid_label_livePreview.setText(_translate("MainWindow", "video preview disabled"))
        self.mid_label_previewFrame.setText(_translate("MainWindow", "^ preview frame ^"))
        self.mid_label_startCropOff.setText(_translate("MainWindow", "start crop off"))
        self.mid_lineEdit_startCropOff.setText(_translate("MainWindow", "0"))
        self.mid_label_endCropOff.setText(_translate("MainWindow", "end crop off"))
        self.mid_lineEdit_endCropOff.setText(_translate("MainWindow", "0"))
        self.mid_radioButton_cropVideo.setText(_translate("MainWindow", "crop video"))
        self.mid_label_cropVideos.setText(_translate("MainWindow", "^ crops all videos cutting off the set number of frames from start and end ^"))
        self.mid_label_Histograms.setText(_translate("MainWindow", "Histograms [original, equalized]:"))
        self.mid_label_histOrig.setText(_translate("MainWindow", "original histogram"))
        self.mid_label_equHist.setText(_translate("MainWindow", "equalized histogram"))
        self.checkBox.setText(_translate("MainWindow", "show original video frame"))
        self.label_vertLayout_VideoSettings.setText(_translate("MainWindow", "Video Settings"))
        self.right_pushButton_calcHist.setText(_translate("MainWindow", "calculate histogram"))
        self.right_pushButton_equalizeHist.setText(_translate("MainWindow", "equalize histogram"))
        self.right_checkBox_useThreshold.setText(_translate("MainWindow", "Use Thresholding"))
        self.right_label_ThreshMin.setText(_translate("MainWindow", "Thresh Min:"))
        self.right_label_ThreshMax.setText(_translate("MainWindow", "Thresh Max"))
        self.right_pushButton_ApplyThreshold.setText(_translate("MainWindow", "apply threshold"))
        self.right_label_Gamma.setText(_translate("MainWindow", "Gamma: "))
        self.right_pushButton_applyGamma.setText(_translate("MainWindow", "apply gamma"))
        self.right_label_Brightness.setText(_translate("MainWindow", "Brightness: "))
        self.right_pushButton_applyBright.setText(_translate("MainWindow", "apply bright"))
        self.right_label_Contrast.setText(_translate("MainWindow", "Contrast: "))
        self.right_pushButton_applyContr.setText(_translate("MainWindow", "apply contr."))
        self.right_checkBox_cannyEdgeDetector.setText(_translate("MainWindow", "canny edge detection"))
        self.right_checkBox_sharpen.setText(_translate("MainWindow", "sharpen image"))
        self.right_pushButton_revertToOriginal.setText(_translate("MainWindow", "revert to original"))
        self.right_pushButton_ApplySettingsToAll.setText(_translate("MainWindow", "apply settings to all selected videos"))
        self.right_label_info.setText(_translate("MainWindow", "Status Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
